# Generated by Django 4.2 on 2023-04-26 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cliente', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=80)),
                ('direccion', models.CharField(blank=True, max_length=80, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_tarjeta', models.IntegerField()),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut_empleado', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=80)),
                ('direccion', models.CharField(blank=True, max_length=80, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('editorial', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('proveedor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'libro',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('rut_tecnico', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=80)),
                ('direccion', models.CharField(blank=True, max_length=80, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tecnico',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('total', models.IntegerField()),
                ('rut_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('rut_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empleado')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_servicio', models.DateField()),
                ('direccion_servicio', models.CharField(max_length=80)),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('detalle_servicio', models.CharField(max_length=200)),
                ('rut_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('rut_tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tecnico')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('tipo_pago', models.CharField(max_length=50)),
                ('id_venta', models.OneToOneField(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, to='app.venta')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('venta_libro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.libro')),
                ('venta_venta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.venta')),
            ],
            options={
                'db_table': 'detalle_compra',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.libro')),
            ],
            options={
                'db_table': 'carrito',
            },
        ),
    ]
